import { AlertTriangle, CheckCircle2, Sparkles } from 'lucide-react';
import { bandOf, scoreBgColor, scoreTextColor } from '@forge/shared';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  cn,
} from '@forge/design-system';

interface MatchInsight {
  title: string;
  explanation: string;
}

export interface MatchScoreData {
  overall_score: number;
  skills_score: number | null;
  experience_score: number | null;
  summary: string | null;
  strengths: MatchInsight[] | null;
  concerns: MatchInsight[] | null;
}

export function ScorePanel({ score }: { score: MatchScoreData | null | undefined }) {
  if (!score) return <UnscoredCard />;

  const band = bandOf(score.overall_score);

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="size-4 text-primary" /> AI match analysis
        </CardTitle>
        <CardDescription>
          Generated by <span className="font-mono">score-fit</span> when the candidate browsed this job.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="flex items-center gap-4">
          <div
            className={cn(
              'grid size-20 place-items-center rounded-2xl text-3xl font-semibold tabular-nums',
              scoreBgColor(score.overall_score),
              scoreTextColor(score.overall_score),
            )}
          >
            {Math.round(score.overall_score)}
          </div>
          <div className="min-w-0 flex-1">
            <div className="text-xs uppercase tracking-wider text-muted-foreground">
              Overall match
            </div>
            <div className="text-lg font-semibold capitalize">{band} fit</div>
            {score.summary ? (
              <p className="mt-1 text-sm text-muted-foreground">{score.summary}</p>
            ) : null}
          </div>
        </div>

        <div className="space-y-3">
          <Breakdown label="Skills" value={score.skills_score} />
          <Breakdown label="Experience" value={score.experience_score} />
        </div>

        <InsightList
          icon={CheckCircle2}
          label="Strengths"
          tone="success"
          items={score.strengths}
        />
        <InsightList
          icon={AlertTriangle}
          label="Concerns"
          tone="warning"
          items={score.concerns}
        />
      </CardContent>
    </Card>
  );
}

function UnscoredCard() {
  return (
    <Card className="border-dashed">
      <CardContent className="px-6 py-8 text-center">
        <div className="mx-auto grid size-10 place-items-center rounded-full bg-muted text-muted-foreground">
          <Sparkles className="size-4" />
        </div>
        <h3 className="mt-3 text-sm font-semibold">No AI score yet</h3>
        <p className="mx-auto mt-1 max-w-xs text-xs text-muted-foreground">
          Scores are generated when a candidate views a job. This candidate may
          have applied before the scoring fired.
        </p>
      </CardContent>
    </Card>
  );
}

function Breakdown({ label, value }: { label: string; value: number | null }) {
  const pct = typeof value === 'number' ? Math.max(0, Math.min(100, value)) : null;
  return (
    <div>
      <div className="flex items-center justify-between text-xs">
        <span className="text-muted-foreground">{label}</span>
        <span className="font-semibold tabular-nums">{pct == null ? '—' : `${Math.round(pct)}%`}</span>
      </div>
      <div className="mt-1.5 h-2 overflow-hidden rounded-full bg-muted">
        <div
          className="h-full rounded-full bg-primary transition-all"
          style={{ width: `${pct ?? 0}%` }}
        />
      </div>
    </div>
  );
}

function InsightList({
  icon: Icon,
  label,
  tone,
  items,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  tone: 'success' | 'warning';
  items: MatchInsight[] | null | undefined;
}) {
  if (!items || items.length === 0) return null;
  const accent = tone === 'success' ? 'text-success-foreground' : 'text-warning-foreground';
  const bg = tone === 'success' ? 'bg-success/10' : 'bg-warning/15';

  return (
    <div>
      <div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
        <Icon className={cn('size-3.5', accent)} />
        {label}
      </div>
      <ul className="space-y-3">
        {items.map((item, i) => (
          <li key={i} className={cn('rounded-md p-3', bg)}>
            <div className="text-sm font-medium">{item.title}</div>
            <p className="mt-0.5 text-xs text-muted-foreground">{item.explanation}</p>
          </li>
        ))}
      </ul>
    </div>
  );
}
