/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCareerRouteImport } from './routes/_app/career'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app/applications/index'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'
import { Route as AppInterviewJobIdRouteImport } from './routes/_app/interview/$jobId'
import { Route as AppApplicationsApplicationIdRouteImport } from './routes/_app/applications/$applicationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewJobIdRoute = AppInterviewJobIdRouteImport.update({
  id: '/interview/$jobId',
  path: '/interview/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsApplicationIdRoute =
  AppApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/career': typeof AppCareerRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/interview/$jobId': typeof AppInterviewJobIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/applications/': typeof AppApplicationsIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/career': typeof AppCareerRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/interview/$jobId': typeof AppInterviewJobIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/applications': typeof AppApplicationsIndexRoute
  '/jobs': typeof AppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/career': typeof AppCareerRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/_app/interview/$jobId': typeof AppInterviewJobIdRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/career'
    | '/dashboard'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/applications/$applicationId'
    | '/interview/$jobId'
    | '/jobs/$jobId'
    | '/applications/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/career'
    | '/dashboard'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/applications/$applicationId'
    | '/interview/$jobId'
    | '/jobs/$jobId'
    | '/applications'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/career'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/applications/$applicationId'
    | '/_app/interview/$jobId'
    | '/_app/jobs/$jobId'
    | '/_app/applications/'
    | '/_app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career': {
      id: '/_app/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/$jobId': {
      id: '/_app/interview/$jobId'
      path: '/interview/$jobId'
      fullPath: '/interview/$jobId'
      preLoaderRoute: typeof AppInterviewJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/$applicationId': {
      id: '/_app/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AppApplicationsApplicationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCareerRoute: typeof AppCareerRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppApplicationsApplicationIdRoute: typeof AppApplicationsApplicationIdRoute
  AppInterviewJobIdRoute: typeof AppInterviewJobIdRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCareerRoute: AppCareerRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppApplicationsApplicationIdRoute: AppApplicationsApplicationIdRoute,
  AppInterviewJobIdRoute: AppInterviewJobIdRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
